export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';
export const ADD_USERS = 'ADD_USERS';

export const REGISTATION_LOADING = 'REGISTATION_LOADING';
export const REGISTRATION_DONE = "REGISTRATION_DONE";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const LOADING_TOKEN = "LOADING_TOKEN";
export const ADD_TOKEN = "ADD_TOKEN";
export const ERROR_TOKEN = "ERROR_TOKEN";

